### ISSUE TITLE
What is the meaning of type number

### ISSUE THREAD

**Issue by shangqing-liu** [GumTreeDiff/gumtree#149] opened 2019-06-07 13:49 UTC
Hi, all

when I used this tool to analyse C function in json format or xml format, but I dont know what is the meaning of the type number just like 
{
"src": "490100 [1479,1481]", 
"dest": "490100 [1491,1493]" 
}
or 
{
"action": "insert-node",
"tree": "240200: 3000 [1209,1213]",
"parent": "20100 [1209,1213]",
 "at": 0
}
Can any one explain the type behind these numbers such as 490100, 240200

thanks.

**Comment by jrfaller** [comment] 2019-06-07 13:53
Hi!

Sorry this is a regression due to an unfinished refactoring. It will be fixed in next version, we know where it comes from.

**Comment by shangqing-liu** [comment] 2019-06-07 14:09
> Hi!
> 
> Sorry this is a regression due to an unfinished refactoring. It will be fixed in next version, we know where it comes from.

So at present, can I understand these numbers represent fixed ast node type, these numbers will not change among different functions?

**Comment by jrfaller** [comment] 2019-06-13 18:28
Yes you are right for a given type, it's id will remain unchanged even parsing an other file in the same language. However, these ids will be removed in the next version where we will rely only on type names.

**Closed** 2019-06-13 18:29 UTC
Labels: question
