### ISSUE TITLE
could not find or load main class on python diff 

### ISSUE THREAD

**Issue by Amirhgh74** [GumTreeDiff/gumtree#174] opened 2020-03-24 17:12 UTC
Hello 

Thanks for the great library. 
I am having a problem running gumTree for python diff. 

I downloaded the latest gumtree and also added pythonparser to PATH and installed the requirements. 
when I run the command `./gumtree diff test1.py test2.py `, I get an error attached below. 

is there anything more I should do? 
I also cloned the latest Java project and built it. 

<img width="569" alt="Screen Shot 2020-03-24 at 9 40 40 PM" src="https://user-images.githubusercontent.com/17717663/77455920-1d6a5600-6e18-11ea-9412-5f1b8645a5de.png">

**Comment by jrfaller** [comment] 2020-03-31 08:07
Duplicate of #152

**Closed by jrfaller** 2020-03-31 08:07 UTC
